# Generated by Django 5.1.3 on 2024-11-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
