# Generated by Django 5.1.3 on 2024-12-08 15:11

import hive_activities.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, validators=[hive_activities.core.validators.validate_no_special_characters]),
        ),
    ]
