# Generated by Django 5.1.3 on 2024-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('TEAM_MEMBER', 'Team Member'), ('PROJECT_MANAGER', 'Project Manager'), ('VIEWER', 'Viewer')], default='TEAM_MEMBER', max_length=20),
        ),
    ]
