# Generated by Django 5.1.3 on 2024-12-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rolerequest_requested_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
