# Generated by Django 5.1.3 on 2024-12-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rolerequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
