# Generated by Django 5.1.3 on 2024-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rolerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
