# Generated by Django 5.1.3 on 2024-12-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_20241204_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='requested_role',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('VIEWER', 'Viewer')], max_length=20),
        ),
    ]
