# Generated by Django 5.1.3 on 2024-12-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmembership_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Team Member'), ('MANAGER', 'Project Manager'), ('VIEWER', 'Viewer')], max_length=20),
        ),
    ]
