# Generated by Django 5.1.3 on 2024-12-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_read_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
