# Generated by Django 5.1.3 on 2024-12-08 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_activity_alter_note_created_by'),
        ('notifications', '0007_notification_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'note', 'created_at')},
        ),
    ]
